# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: alpine:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375


services:
- docker:dind

# tmp/ folder must be added to .gitignore

before_script:
  - echo "Codacy CLI on GitLab Pipeline!"
  - mkdir $CI_PROJECT_DIR/tmp 
  - export CODACY_TMP_DIRECTORY=$CI_PROJECT_DIR/tmp
  - echo $CODACY_TMP_DIRECTORY
  - apk --no-cache add unzip openjdk8-jre make curl bash docker gradle
  - docker version

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build:
  stage: build
  script:
    - gradle build
    - wget "$(curl -s https://api.github.com/repos/codacy/codacy-analysis-cli/releases/latest | grep "http.*codacy-analysis-cli-assembly" | cut -d ':' -f 2,3 | tr -d \" | sed -e "s/ //g")" -O $CODACY_TMP_DIRECTORY/codacy-analysis-cli.jar -q
    - java -jar $CODACY_TMP_DIRECTORY/codacy-analysis-cli.jar analyze --tool spotbugs --directory $CI_PROJECT_DIR --max-allowed-issues 9999999 --upload --verbose --tmp-directory $CODACY_TMP_DIRECTORY
